name = "Antares Unit Pack"
uid = "6aa65d2a-5926-11dc-8314-0800200c9a08"
version = 2.5
description = "Adds few more T3 and T4 units."
author = "(edit by)AntaresOne"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = {}
requiresNames = {}
conflicts = {}
before = {}
after = {}