# autogenerated file - DO NOT EDIT THIS FILE UNDER ANY CIRCUMSTANCES
# USE LocStrings.xls INSTEAD TO EDIT STRINGS

expshdaeon001_desc="Experimentální Generátor Štítů"
expshdaeon001_help="Experimentální Generátor Štítů"
expshdaeon001_name="Oslnění"
FAB4101_desc="Jednoduchý Generátor Štítů"
FAB4101_help="Jednoduchý Generátor Štítů"
FAB4101_Name="Jiskra"

expshduef001_desc="Experimentální Generátor Štítů"
expshduef001_help="Experimentální Generátor Štítů"
expshduef001_name="ESD Pulse"
FEB4101_desc="Jednoduchý Generátor Štítů"
FEB4101_help="Jednoduchý Generátor Štítů"
FEB4101_Name="LSD Pulse"

expshdcyb001_desc="Experimentální Generátor Štítů"
expshdcyb001_help="Experimentální Generátor Štítů"
expshdcyb001_name="ED6"
FRL0101_desc="Mobilní Generátor Štítů"
FRL0101_help="Mobilní Generátor Štítů"
FRL0101_name="ED0"

expshdser001_desc="Experimentální Generátor Štítů"
expshdser001_help="Experimentální Generátor Štítů"
expshdser001_name="Athanuhthethuum"
FSB4101_desc="Jednoduchý Generátor Štítů"
FSB4101_help="Jednoduchý Generátor Štítů"
FSB4101_Name="Atha-Istle"


ability_hugeshielddome="Obrovský štítový dóm"
