name = "AutoTML"
version = "1.1.1"
copyright = "Copyright © 2008, Chojin"
author = "Chojin, scripts are modified from examples provided by Resin_Smoker"
description = "Tactical missile launchers will automatically fire upon targets using tracking missiles, and dynamically retarget upon losing their target or to avoid overkill."
icon = "/mods/AutoTML/textures/mod_icon.dds"
selectable = true
exclusive = false
ui_only = false
uid = "a6bl2udx-5q85-96w1-h684-y32k58208471"
