name = "Nuke colide"
uid = "4c3fe730-7305-11dd-ad8b-0800200c9a66"
version = 1
copyright = "Meredith/Eluvatar"
description = "this makes the nuke colide and detonate with sheilds"
author = "Meredith/Eluvatar"
url = "None"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = {}
requiresNames = {}
conflicts = {}
before = {}
after = {}
