##****************************************************************************
#**  File     :  lua/ui/help/unitdescriptions.lua
#**  Author(s):  Lt_Hawkeye
#****************************************************************************
 

#Descriptions for new units in BlackOps
#Cybran
    
	-- AEON
	Description['waa0305'] = "A bomber that excels at engaging large groups of T3/T2/T1 units or T2/T1 structures."
	Description['wab0201'] = "Constructs Tech 2 land units. Upgradeable."
   	Description['wab0202'] = "Constructs Tech 2 air units. Upgradeable."
   	Description['wab0203'] = "Constructs Tech 2 naval units. Upgradeable." 
   	Description['wab0301'] = "Constructs Tech 3 land units. Highest tech level available."
   	Description['wab0302'] = "Constructs Tech 3 air units. Highest tech level available."
   	Description['wab0303'] = "Constructs Tech 3 naval units. Highest tech level available."
	Description['wab1302'] = "A high tech Hydrocarbon facility. Generates Energy."
	Description['wab1303'] = "A high tech resource facility. Generates Mass and Energy."
	Description['wab2303'] = "Tier 3 Point Defense."
	Description['wal0305'] = "Slow-moving, heavily armored assault tank. Designed to engage base defenses and structures."
	Description['wal0309'] = "Mobile anti-air unit. Effective against high-end enemy air units."
	Description['wal0401'] = "Sacred assault bot. Incinerates enemy units and structures with Phason laser. Also equipped with tractor beam. Pulls in and crushes mobile enemy units."
	Description['wal4404'] = "Experimental Mobile Assault Mecha."
	Description['was0332'] = "Heavy Battleship designed to bombard at long ranges."
	
	--EXP Upgrades
	Description['wal4404-ptsg'] = "Strengthens the NovaCat with a Light Personal Shield."
	
   Description['wal0001'] = "Houses Commander. Combination barracks and command center. Contains all the blueprints necessary to build a basic army from scratch."
   Description['wal0001-aes'] = "Expands the number of available schematics and increases the ACU's build speed and maximum health.\n\nUnlock Tech 2 Construction\n+3000 Health\nArmour Regen:+20\nBuild Speed:+30"
   Description['wal0001-cd'] = "Creates a Quantum Stasis Field around the ACU. Immobilizes enemy units within its radius. High Energy Consumption.\n\nInstalls Chrono Dampener"
   Description['wal0001-plg'] = "Adds a Phason Laser to the ACU. Increases Health and Regen.\n\n+5000 Health\n+25 Armour Regen\nInstalls Phason Laser Generator"
   Description['wal0001-ess'] = "Greatly expands the range of the standard onboard ACU sensor systems.\n\n+50 Vision Radius\n+100 Omni Radius"
   Description['wal0001-ees'] = "Replaces the Tech 2 Engineering Suite. Expands the number of available schematics and further increases the ACU's build speed and maximum health.\n\nUnlock Tech 3 Construction\n+6000 Health\nArmour Regen:+40\nBuild Speed:+80"
   Description['wal0001-fpu'] = "Enhancments the plasma capacitors of the disruptor. Increases Damage.\n\n+100 Disruptor Damage"
   Description['wal0001-ras'] = "Increases ACU's resource generation.\n\nNew Mass Production:18\nNew Energy Production:2700"
   Description['wal0001-eras'] = "Requires Resource Allocation System. Further increases ACU's resource generation.\n\nNew Mass Production:36\nNew Energy Production:5400"
   Description['wal0001-ptsg'] = "Creates a protective shield around the ACU. Requires Energy to run.\n\nShield Health:29000\nShield Regen:37\nShield Type:Personal\nShield Mainntenance:250"
   Description['wal0001-phtsg'] = "Enhances the protective shield around the ACU. Requires Energy to run. \n\nShield Health:44000\nShield Regen:44\nShield Type:Personal\nShield Mainntenance:500"
   Description['wal0001-phtsg_aa'] = "Enables a pair of Anti-Air batteries on the ACU.\n\nEnables Sonic Pulse Batteries"
   Description['wal0001-eras_aa'] = "Enables a pair of Anti-Air batteries on the ACU.\n\nEnables Sonic Pulse Batteries"
   Description['wal0001-pqt'] = "Adds teleporter. Requires considerable Energy to activate.\n\nInstalls Teleporter"
   Description['wal0001-hsa'] = "Adds Anti-Missile Capabilities.\n\nEnables TML Defenses"
   Description['wal0001-spd'] = "Increases ACU speed by 50%. \n\nIncreased speed by 50%"
   Description['wal0001-ctl'] = "Enables teh ACU's Chrono Torpedo Tube System.\n\nInstalls Torpedo Launcher"
	
	
	
	
			
			    -- UEF
	Description['wea0305'] = "High-end Rocket Aircraft. Designed to only assault ground forces."
	Description['web0201'] = "Constructs Tech 2 land units. Upgradeable."
   	Description['web0202'] = "Constructs Tech 2 air units. Upgradeable."
   	Description['web0203'] = "Constructs Tech 2 naval units. Upgradeable." 
   	Description['web0301'] = "Constructs Tech 3 land units. Highest tech level available."
	Description['web0301a'] = "Constructs Tech 3 land units. Highest tech level available."
   	Description['web0302'] = "Constructs Tech 3 air units. Highest tech level available."
   	Description['web0303'] = "Constructs Tech 3 naval units. Highest tech level available."
	Description['web0401'] = "Experimental Intel Center with Radar and Omni."
	Description['web2204'] = "Anti-air tower. Designed to engage mid-level aircraft."
	Description['web1302'] = "A high tech Hydrocarbon facility. Generates Energy."
	Description['web1303'] = "A high tech resource facility. Generates Mass and Energy."
	Description['wel0104'] = "Mobile anti-air defense. Effective against low-end enemy air units."
	Description['wel0201'] = "Medium Tank. Equipped with a medium gauss cannon."
	Description['wel0207'] = "Mobile Tactical Missile Defense."
	Description['wel0302'] = "Shielded heavy assault bot. Armed with two cannons and anti-air railgun."
	Description['wel0303'] = "A Heavy Shielded Assault tank with anti-air capabilities."
	Description['wel0304'] = "Slow-moving heavy artillery. Must be stationary to fire."
	Description['wel0305'] = "A heavily armed amphibious tank, armed with a personal shield and AA capabilities."
	Description['wel0309'] = "Mobile anti-air unit. Effective against high-end enemy air units."
	Description['wel1409'] = "Experimental Bombardment Tank."
	Description['wes0303'] = "Heavily armoured Escort ship. Can attack all types of targets including Subs and Aircraft."
	Description['wes0401'] = "Experimental Naval Vessel designed to engage shore targets and other ships."
	Description['wel0416'] = "The ultimate force of the UEF Military. The Dragonite is a very deadly weapon capable of a wiping out vast armies with its many weapons. Its Anti-Air weaponry is capable of taking out almost any aircraft quickly and effeciently. The Wyvern is the only self aware weapon in the UEF army and is know to sometimes assault the enemy on its own accord."
	
		-- Battle Pack UEF ACU STUFF
     Description['wel0001'] = "Houses Commander. Combination barracks and command center. Contains all the blueprints necessary to build a basic army from scratch."
     Description['wel0001-tm'] = "Mounts a tactical cruise missile launcher onto the back of the ACU.\n\nInstalls Tactical Missile Launcher"
     Description['wel0001-aes'] = "Expands the number of available schematics and increases the ACU's build speed and maximum health.\n\nUnlock Tech 2 Construction\n+3000 Health\nArmour Regen:+20\nBuild Speed:+30"
     Description['wel0001-dsu'] = "Greatly increases the speed at which the ACU repairs itself.\n\nRegen Rate:200"
     Description['wel0001-ees'] = "Replaces the Tech 2 Engineering Suite. Expands the number of available schematics and further increases the ACU's build speed and maximum health.\n\nUnlock Tech 3 Construction\n+6000 Health\nArmour Regen:+15\nBuild Speed:+90"
     Description['wel0001-hamc'] = "Increases main cannon's damage output by several factors. Also increases range of main cannon and Overcharge.\n\n+100 Zepher Damage\nNew Range:30"
     Description['wel0001-srtn'] = "Adds a short-range tactical nuke.\n\nInstalls Nuclear Tactical Missile Launcher"
     Description['wel0001-pqt'] = "Adds teleporter. Requires considerable Energy to activate.\n\nInstalls Teleporter"
     Description['wel0001-sgf'] = "Expands the radius of the ACU's personal shield. Requires Energy to run.\n\nShield Health:36000\nShield Regen:42\nShield Type:Bubble\nBubble Size:16\nShield Mainntenance:500"
     Description['wel0001-isb'] = "Increases ACU's resource generation.\n\nNew Mass Production:14\nNew Energy Production:3300"
     Description['wel0001-psg'] = "Creates a protective shield around the ACU. Requires Energy to run.\n\nShield Health:24000\nShield Regen:35\nShield Type:Personal\nShield Mainntenance:250"
	 Description['wel0001-hpsg'] = "Enables a pair of Anti-Air Batteries.\n\nInstalls Flayer SAM Launchers"
     Description['wel0001-led'] = "Engineering Drone acts as a secondary Engineer. Assists the ACU where applicable.\n\nInstalls Left Engineering Drone"
     Description['wel0001-red'] = "Adds a second Engineering Drone. Requires an initial Engineering Drone.\n\nInstalls Right Engineering Drone"
	 Description['wel0001-sg'] = "Enables a pair of shoulder mounted gauss guns.\n\nInstalls Shoulder Gauss Cannons"
	 Description['wel0001-gat'] = "Enables the ACUs secondary weapon system.\n\nInstalls Heavy Plasma Gatling Cannon"
	 Description['wel0001-atl'] = "Enables a Angler Torpedo Launcher on the ACU to defend against naval attacks while submerged.\n\nInstalls Torpedo Launcher"
		--EXP Upgrades
	Description['wel1409-sgf'] = "Creates a protective shield around the Fatboy 2. Requires Energy to run."
	
	-- CYBRAN
	Description['wra0202'] = "Mid-level air fighter.  Excellent AA capabilities. Effective against enemy gunships and bombers."
	Description['wra0303'] = "High-end gunship."
	Description['wrb0201'] = "Constructs Tech 2 land units. Upgradeable."
   	Description['wrb0202'] = "Constructs Tech 2 air units. Upgradeable."
   	Description['wrb0203'] = "Constructs Tech 2 naval units. Upgradeable." 
   	Description['wrb0301'] = "Constructs Tech 3 land units. Highest tech level available."
   	Description['wrb0302'] = "Constructs Tech 3 air units. Highest tech level available."
   	Description['wrb0303'] = "Constructs Tech 3 naval units. Highest tech level available."
	Description['wrb0304'] = "Automatically repairs, reclaims, assists or captures any unit within its operational radius."
	Description['wrb1302'] = "A high tech Hydrocarbon facility. Generates Energy."
	Description['wrb1303'] = "A high tech resource facility. Generates Mass and Energy."
	Description['wrb2302'] = "High End Artillery structure. Requires energy to fire."
	Description['wrb4207'] = "Generates a heavy shield around units and structures within its radius."
	Description['wrb4302'] = "Tier 3 Point Defense."
	Description['wrl0301'] = "A heavy armoured assault tank, equipped with a personal stealth capabilities."
	Description['wrl1211'] = "Mobile rocket artillery designed to engage large targets."
	Description['wrl0302'] = "Mid level assault tank."
	Description['wrl0303'] = "Heavy Bot designed for Base offense."
	Description['wrl0305'] = "Designed to strike high-value targets from a distance."
	Description['wrl0309'] = "Mobile anti-air unit. Effective against high-end enemy air units."
	Description['wrl0402'] = "Experimental, amphibious mobile fortress. Equipped with battleship-level weapons and armor. Its shield consumes Energy."
	Description['wrl1466'] = "The Cybrans ultimate walking fortress. Fortified with heavy defenses and weaponry."
	Description['wrs0303'] = "Heavy bombardment battleship."
	Description['wrs0401'] = "Experimental battleship armed with Heavy cannons, Anti-Air weapons, and Torpedos."
	
	-- CYBRAN ACU STUFF
			-- Battle Pack CYBRAN ACU STUFF
    Description['wrl0001'] = "Houses Commander. Combination barracks and command center. Contains all the blueprints necessary to build a basic army from scratch."
    Description['wrl0001-ras'] = "Increases ACU's resource generation.\n\nNew Mass Production:15\nNew Energy Production:4000"
    Description['wrl0001-pcg'] = "Cloaks the ACU from optical sensors and increases maximum health. Can be detected by Omni Sensors. Requires Energy to run.\n\nInstalls Cloak Generator"
    Description['wrl0001-psg'] = "Hides the ACU from radar. Requires Energy to run.\n\nEnables Radar Stealth"
    Description['wrl0001-pqt'] = "Adds teleporter. Requires considerable Energy to activate.\n\nInstalls Teleporter"
    Description['wrl0001-aes'] = "Expands the number of available schematics and increases the ACU's build speed and maximum health.\n\nUnlock Tech 2 Construction\n+3500 Health\nArmour Regen:+20\nBuild Speed:+30"
    Description['wrl0001-ees'] = "Replaces the Tech 2 Engineering Suite. Expands the number of available schematics and further increases the ACU's build speed and maximum health.\n\nUnlock Tech 3 Construction\n+7000 Health\nArmour Regen:+15\nBuild Speed:+90"
    Description['wrl0001-acu'] = "Increases main cannon's rate of fire and range. Also increases range of the Molecular Ripper and Overcharge.\n\nNew Range:30\nNew RoF:2"
    Description['wrl0001-dual'] = "Equips the ACU with a second ripper cannon.\n\nInstalls Secondary Ripper Cannon"
    Description['wrl0001-ntt'] = "Equips the ACU with a standard Cybran Nanite torpedo tube and sonar.\n\nInstalls Torpedo Launcher"
	Description['wrl0001-fc'] = "Increases the damage of all the ACUs weapon Systems.\n\nAnti-Air Damage:+25\nTorpedo Damage:+50\nRipper Damage:+100"
	 Description['wrl0001-cpsg'] = "Equips the ACU with a Personal Shield Generator. Requires energy to run.\n\nShield Health:24000\nShield Regen:35\nShield Type:Personal\nShield Mainntenance:250"
	 Description['wrl0001-hcpsg'] = "Upgrades the ACU's personal shield.\n\nShield Health:44000\nShield Regen:44\nShield Type:Personal\nShield Mainntenance:500"
    Description['wrl0001-eras_aa'] = "Enables a pair of Anti-Air batteries on the ACU.\n\nInstalls Electron Autocannons"
   Description['wrl0001-hcpsg_aa'] = "Enables a pair of Anti-Air batteries on the ACU.\n\nInstalls Electron Autocannons"
	 
		-- SERAPHIM
	Description['wsa0201'] = "A medium fighter."
	Description['wsa0306'] = "A heavy Air Transport. Equipped with AA Turrets and a Shield."
	Description['wsb0201'] = "Constructs Tech 2 land units. Upgradeable."
   	Description['wsb0202'] = "Constructs Tech 2 air units. Upgradeable."
   	Description['wsb0203'] = "Constructs Tech 2 naval units. Upgradeable." 
   	Description['wsb0301'] = "Constructs Tech 3 land units. Highest tech level available."
   	Description['wsb0302'] = "Constructs Tech 3 air units. Highest tech level available."
   	Description['wsb0303'] = "Constructs Tech 3 naval units. Highest tech level available."
	Description['wsb1302'] = "A high tech Hydrocarbon facility. Generates Energy."
	Description['wsb1303'] = "Resource Center. Generates large amounts of Mass and Energy."
	Description['wsb1401'] = "An Experimental shield generator with Anti-Air Capabilities. Requires large amounts of energy to run."
	Description['wsl0202'] = "Heavy tank equipped with a single cannon and a shield generator."
	Description['wsl0205'] = "A shielded spider bot. Can also intercept aircraft."
	Description['wsl0302'] = "Shielded heavy assault bot. Armed with 4 cannons and personal shield."
	Description['wsl0308'] = "Heavily armed tank, equipped with a enhanced stunner."
	Description['wsl2303'] = "The Seraphims version of the Wagon of Death."
	Description['wsl0404'] = "A experimental assault tank. Armed with Anti-Air capabilities, a shield done, and heavy weaponry."
	Description['wss0301'] = "Heavily armed battleship capable of engaging all targets."
	
	-- SERAPHIM ACU STUFF
	Description['wsl0001'] = "<LOC Unit_Description_0420> Houses Commander. Combination barracks and command center. Contains all the blueprints necessary to build a basic army from scratch."
	Description['wsl0001-pqt'] = "Adds teleporter. Requires considerable Energy to activate.\n\nInstalls Teleporter"
    Description['wsl0001-dss'] = "Increases the speed at which the ACU repairs itself. Also increases hit points.\n\nHealth:+6000\nRegen Rate:+75"
	Description['wsl0001-adss'] = "Further increases the speed at which the ACU repairs itself. Also increases hitpoints.\n\nHealth:+20000\nRegen Rate:+150"
	Description['wsl0001-ras'] = "Increases ACU's resource generation.\n\nNew Mass Production:16\nNew Energy Production:3000"
	Description['wsl0001-eras'] = "Further increases ACU's resource generation.\n\nNew Mass Production:32\nNew Energy Production:6000"
	Description['wsl0001-aes'] = "Expands the number of available schematics and increases the ACU's build speed and maximum health.\n\nUnlock Tech 2 Construction\n+3000 Health\nArmour Regen:+20\nBuild Speed:+30"
	Description['wsl0001-ees'] = "Replaces the Tech 2 Engineering Suite. Expands the number of available schematics and further increases the ACU's build speed and maximum health.\n\nUnlock Tech 3 Construction\n+4000 Health\nArmour Regen:+15\nBuild Speed:+90"
	Description['wsl0001-cba'] = "Increases the damage inflicted by ACU's primary weapon. Adds area-of-effect damage.\n\nChronotron Cannon Damage:+300\nDamage Radius:+2"
	Description['wsl0001-nrf'] = "Automatically speeds up the repair speed of nearby units.\n\nInstalls Restoration Field\nRadius:15"
    Description['wsl0001-anrf'] = "Further speeds up the repair speed of nearby units.\n\nRadius:25"
	Description['wsl0001-hsa'] = "Increases main cannon's rate of fire and range. Also increases range of Overcharge.\n\nChronotron Cannon Rof:2\nNew Range:30"
	Description['wsl0001-tml'] = "Mounts a tactical cruise missile launcher onto the back of the ACU.\n\nInstalls Tactical Missile Launcher"
	Description['wsl0001-spsg'] = "Equips the ACU with a Personal Shield Generator. Requires energy to run.\n\nShield Health:24000\nShield Regen:35\nShield Type:Personal\nShield Mainntenance:250"
	Description['wsl0001-hspsg'] = "Upgrades the ACU's personal shield.\n\nShield Health:44000\nShield Regen:44\nShield Type:Personal\nShield Mainntenance:500"
	Description['wsl0001-hspsg_aa'] = "Enables a pair of Anti-Air Batteries.\n\nInstalls Olaris AA Artillery Cannons"
	Description['wsl0001-tml_aa'] = "Enables a pair of Anti-Air Batteries.\n\nInstalls Olaris AA Artillery Cannons"
	Description['wsl0001-torp'] = "Equips the ACU with a standard torpedo tube and sonar.\n\nInstalls Torpedo launcher"
	Description['wsl0001-tahu'] = "Adds a secondary cannon to the acu, increasing its overall damage.\n\nInstalls Aireau Bolter Cannon"